# Generated by Django 5.2.4 on 2025-07-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_is_approved_newsletter_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='journalists',
            new_name='journalist',
        ),
    ]
