# Generated by Django 5.2.4 on 2025-07-15 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, default=None, related_name='subscribed_publishers', to=settings.AUTH_USER_MODEL),
        ),
    ]
