# Generated by Django 5.2.4 on 2025-07-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_subscribed_publishers'),
        ('news', '0005_rename_journalists_article_journalist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, default=None, related_name='subscribed_publishers', to='news.publisher'),
        ),
    ]
