# Generated by Django 5.2.4 on 2025-07-25 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_subscribed_journalists_and_more'),
        ('news', '0006_alter_publisher_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribed_journalists',
            field=models.ManyToManyField(blank=True, default=None, related_name='subscribed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, default=None, related_name='subscribed_users', to='news.publisher'),
        ),
    ]
